#!/usr/bin/env bash

action=$1
version=$2

echo post uninstall [[name]] \$1 = $1 >>/tmp/rpminst

if [ "$action" == "remove" ] || [ "$action" == "purge" ]; then
  # It's an un-installation

  getent passwd "[[username]]" 2>&1 1>/dev/null
  if [ $? == 0 ]; then
    echo "Logging off user [[username]]"
    /usr/bin/pkill -KILL -u [[username]] 2>&1 1>/dev/null
  fi

  rm -rf [[target_artifactory_home]]/work [[target_artifactory_home]]/temp 2>/dev/null

  # Ignoring user folders since the home dir is deleted already by the RPM spec
  echo "Removing local user [[username]]"
  ( grep -q [[username]] /etc/passwd &&
  /usr/sbin/userdel [[username]] 2>/dev/null)

  EXISTING_GROUP="`grep [[group_name]] /etc/group | awk -F ':' '{ print $1 }' 2>/dev/null`"
  if [ "$EXISTING_GROUP" == "[[group_name]]" ]; then
    echo "Removing group [[group_name]]"
    /usr/sbin/groupdel [[group_name]]
  fi

  if [ "$action" == "purge" ]; then
    echo "Purging artifactory"
    rm -rf /etc/opt/jfrog/* /var/opt/jfrog/* [[target_tomcat_home]]/webapps [[target_tomcat_home]]/work
  fi

fi
exit 0