#!/usr/bin/env bash

action=$1
version=$2

if [ "$action" = "configure" ]; then
  echo "Adding the artifactory service to auto-start"
  /usr/sbin/update-rc.d artifactory defaults >/dev/null || $?

  echo
  echo "The installation of Artifactory has completed successfully."
  echo
  echo "PLEASE NOTE: You can recover a backup done with Artifactory packages 3.0 and above using '/opt/jfrog/artifactory/bin/recover.backup.sh'. For upgrading from previous version of Artifactory please refer to the wiki http://wiki.jfrog.org/confluence/display/RTF/Upgrading+Artifactory"
  echo "PLEASE NOTE: It is highly recommended to use Artifactory in conjunction with MySQL. You can easily configure this setup using '/opt/jfrog/artifactory/bin/configure.mysql.sh'."
  echo
fi
