#!/bin/bash
#
# Startup script for Tomcat Servlet Engine
#
# chkconfig: 345 86 14
# description: Artifactory Tomcat Servlet Engine
# processname: artifactory
# pidfile: /var/run/artifactory.pid
#

# Read default Artifactory environment variables from etc
. /etc/artifactory/default

# User under which tomcat will run
NORMAL_PORT=8015
LOCK_FILE=/var/lock/subsys/artifactory
export CATALINA_PID=/var/run/artifactory.pid

if [ -z "$ARTIFACTORY_USER" ]; then
    # Will run as current user (may be root!!!)
    ARTIFACTORY_USER=$USER
fi

# Make sure the pid file is writable by Artifactory user
touch $CATALINA_PID
chown $ARTIFACTORY_USER $CATALINA_PID

RETVAL=0

# start, debug, stop, and status functions
start() {
    # Start Tomcat in normal mode
    SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep $NORMAL_PORT|wc -l`
    if [ $SHUTDOWN_PORT -ne 0 ]; then
        echo "Artifactory Tomcat already started"
    else
        echo "Starting tomcat..."
        su -l $ARTIFACTORY_USER -c '/opt/tomcat/artifactory/bin/startup.sh'
        SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep $NORMAL_PORT|wc -l`
	started=false
	nbSeconds=1
        while [ $SHUTDOWN_PORT -eq 0 ] && [ $nbSeconds -lt 30 ]; do
            sleep 1
	    let "nbSeconds = $nbSeconds + 1"
            SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep $NORMAL_PORT|wc -l`
	    if [ $SHUTDOWN_PORT -gt 0 ]; then
		started=true
	    fi
        done
	if [ $started = false ]; then
		echo "ERROR: Artifactory Tomcat server did not start in 30 seconds,Please check logs"
		exit 1
	fi
        RETVAL=$?
        echo "Artifactory Tomcat started in normal mode"
        [ $RETVAL=0 ] && touch $LOCK_FILE
    fi
}

stop() {
    SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep $NORMAL_PORT|wc -l`
    if [ $SHUTDOWN_PORT -eq 0 ]; then
        echo "Artifactory Tomcat already stopped"
    else
        echo "Stopping Artifactory Tomcat..."
        su -l $ARTIFACTORY_USER -c '/opt/tomcat/artifactory/bin/shutdown.sh'
        SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep $NORMAL_PORT|wc -l`
        while [ $SHUTDOWN_PORT -ne 0 ]; do
            sleep 1
            SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep $NORMAL_PORT|wc -l`
        done
        RETVAL=$?
        echo "Artifactory Tomcat stopped"
        [ $RETVAL=0 ] && rm -f "$LOCK_FILE" "$CATALINA_PID"
    fi
}

status() {
    SHUTDOWN_PORT=`netstat -vatn|grep LISTEN|grep $NORMAL_PORT|wc -l`
    if [ $SHUTDOWN_PORT -eq 0 ]; then
        echo "Artifactory Tomcat stopped"
    else
        echo "Artifactory Tomcat running"
    fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  redebug)
        stop
        debug
        ;;
  status)
        status
        ;;
  *)
  echo "Usage: $0 {start|stop|restart|redebug|status}"
  exit 1
esac

exit $RETVAL
